import "./globals.css";
import type { Metadata } from "next";
import {
	ClerkProvider,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
} from "@clerk/nextjs";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={`antialiased`}>
					<SignedOut>
						<SignInButton />
						<SignUpButton />
					</SignedOut>

					<SignedIn>{children}</SignedIn>
				</body>
			</html>
		</ClerkProvider>
	);
}
